/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdvancedRouteImport } from './routes/advanced'
import { Route as AcceptRouteImport } from './routes/accept'
import { Route as BenchRouteRouteImport } from './routes/bench/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BenchIndexRouteImport } from './routes/bench/index'
import { Route as BenchVerifyRouteImport } from './routes/bench/verify'
import { Route as BenchExchangeRouteImport } from './routes/bench/exchange'
import { Route as BenchAcceptRouteImport } from './routes/bench/accept'
import { Route as ApiPeerjsIndexRouteImport } from './routes/api/peerjs/index'
import { Route as ApiPeerjsIdRouteImport } from './routes/api/peerjs/id'
import { Route as ApiPeerjsKeyPeersRouteImport } from './routes/api/peerjs/$key/peers'

const AdvancedRoute = AdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptRoute = AcceptRouteImport.update({
  id: '/accept',
  path: '/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchRouteRoute = BenchRouteRouteImport.update({
  id: '/bench',
  path: '/bench',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchIndexRoute = BenchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BenchRouteRoute,
} as any)
const BenchVerifyRoute = BenchVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => BenchRouteRoute,
} as any)
const BenchExchangeRoute = BenchExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => BenchRouteRoute,
} as any)
const BenchAcceptRoute = BenchAcceptRouteImport.update({
  id: '/accept',
  path: '/accept',
  getParentRoute: () => BenchRouteRoute,
} as any)
const ApiPeerjsIndexRoute = ApiPeerjsIndexRouteImport.update({
  id: '/api/peerjs/',
  path: '/api/peerjs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeerjsIdRoute = ApiPeerjsIdRouteImport.update({
  id: '/api/peerjs/id',
  path: '/api/peerjs/id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeerjsKeyPeersRoute = ApiPeerjsKeyPeersRouteImport.update({
  id: '/api/peerjs/$key/peers',
  path: '/api/peerjs/$key/peers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bench': typeof BenchRouteRouteWithChildren
  '/accept': typeof AcceptRoute
  '/advanced': typeof AdvancedRoute
  '/bench/accept': typeof BenchAcceptRoute
  '/bench/exchange': typeof BenchExchangeRoute
  '/bench/verify': typeof BenchVerifyRoute
  '/bench/': typeof BenchIndexRoute
  '/api/peerjs/id': typeof ApiPeerjsIdRoute
  '/api/peerjs/': typeof ApiPeerjsIndexRoute
  '/api/peerjs/$key/peers': typeof ApiPeerjsKeyPeersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept': typeof AcceptRoute
  '/advanced': typeof AdvancedRoute
  '/bench/accept': typeof BenchAcceptRoute
  '/bench/exchange': typeof BenchExchangeRoute
  '/bench/verify': typeof BenchVerifyRoute
  '/bench': typeof BenchIndexRoute
  '/api/peerjs/id': typeof ApiPeerjsIdRoute
  '/api/peerjs': typeof ApiPeerjsIndexRoute
  '/api/peerjs/$key/peers': typeof ApiPeerjsKeyPeersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bench': typeof BenchRouteRouteWithChildren
  '/accept': typeof AcceptRoute
  '/advanced': typeof AdvancedRoute
  '/bench/accept': typeof BenchAcceptRoute
  '/bench/exchange': typeof BenchExchangeRoute
  '/bench/verify': typeof BenchVerifyRoute
  '/bench/': typeof BenchIndexRoute
  '/api/peerjs/id': typeof ApiPeerjsIdRoute
  '/api/peerjs/': typeof ApiPeerjsIndexRoute
  '/api/peerjs/$key/peers': typeof ApiPeerjsKeyPeersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bench'
    | '/accept'
    | '/advanced'
    | '/bench/accept'
    | '/bench/exchange'
    | '/bench/verify'
    | '/bench/'
    | '/api/peerjs/id'
    | '/api/peerjs/'
    | '/api/peerjs/$key/peers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept'
    | '/advanced'
    | '/bench/accept'
    | '/bench/exchange'
    | '/bench/verify'
    | '/bench'
    | '/api/peerjs/id'
    | '/api/peerjs'
    | '/api/peerjs/$key/peers'
  id:
    | '__root__'
    | '/'
    | '/bench'
    | '/accept'
    | '/advanced'
    | '/bench/accept'
    | '/bench/exchange'
    | '/bench/verify'
    | '/bench/'
    | '/api/peerjs/id'
    | '/api/peerjs/'
    | '/api/peerjs/$key/peers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchRouteRoute: typeof BenchRouteRouteWithChildren
  AcceptRoute: typeof AcceptRoute
  AdvancedRoute: typeof AdvancedRoute
  ApiPeerjsIdRoute: typeof ApiPeerjsIdRoute
  ApiPeerjsIndexRoute: typeof ApiPeerjsIndexRoute
  ApiPeerjsKeyPeersRoute: typeof ApiPeerjsKeyPeersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/advanced': {
      id: '/advanced'
      path: '/advanced'
      fullPath: '/advanced'
      preLoaderRoute: typeof AdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept': {
      id: '/accept'
      path: '/accept'
      fullPath: '/accept'
      preLoaderRoute: typeof AcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench': {
      id: '/bench'
      path: '/bench'
      fullPath: '/bench'
      preLoaderRoute: typeof BenchRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench/': {
      id: '/bench/'
      path: '/'
      fullPath: '/bench/'
      preLoaderRoute: typeof BenchIndexRouteImport
      parentRoute: typeof BenchRouteRoute
    }
    '/bench/verify': {
      id: '/bench/verify'
      path: '/verify'
      fullPath: '/bench/verify'
      preLoaderRoute: typeof BenchVerifyRouteImport
      parentRoute: typeof BenchRouteRoute
    }
    '/bench/exchange': {
      id: '/bench/exchange'
      path: '/exchange'
      fullPath: '/bench/exchange'
      preLoaderRoute: typeof BenchExchangeRouteImport
      parentRoute: typeof BenchRouteRoute
    }
    '/bench/accept': {
      id: '/bench/accept'
      path: '/accept'
      fullPath: '/bench/accept'
      preLoaderRoute: typeof BenchAcceptRouteImport
      parentRoute: typeof BenchRouteRoute
    }
    '/api/peerjs/': {
      id: '/api/peerjs/'
      path: '/api/peerjs'
      fullPath: '/api/peerjs/'
      preLoaderRoute: typeof ApiPeerjsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/peerjs/id': {
      id: '/api/peerjs/id'
      path: '/api/peerjs/id'
      fullPath: '/api/peerjs/id'
      preLoaderRoute: typeof ApiPeerjsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/peerjs/$key/peers': {
      id: '/api/peerjs/$key/peers'
      path: '/api/peerjs/$key/peers'
      fullPath: '/api/peerjs/$key/peers'
      preLoaderRoute: typeof ApiPeerjsKeyPeersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BenchRouteRouteChildren {
  BenchAcceptRoute: typeof BenchAcceptRoute
  BenchExchangeRoute: typeof BenchExchangeRoute
  BenchVerifyRoute: typeof BenchVerifyRoute
  BenchIndexRoute: typeof BenchIndexRoute
}

const BenchRouteRouteChildren: BenchRouteRouteChildren = {
  BenchAcceptRoute: BenchAcceptRoute,
  BenchExchangeRoute: BenchExchangeRoute,
  BenchVerifyRoute: BenchVerifyRoute,
  BenchIndexRoute: BenchIndexRoute,
}

const BenchRouteRouteWithChildren = BenchRouteRoute._addFileChildren(
  BenchRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchRouteRoute: BenchRouteRouteWithChildren,
  AcceptRoute: AcceptRoute,
  AdvancedRoute: AdvancedRoute,
  ApiPeerjsIdRoute: ApiPeerjsIdRoute,
  ApiPeerjsIndexRoute: ApiPeerjsIndexRoute,
  ApiPeerjsKeyPeersRoute: ApiPeerjsKeyPeersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
