/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdvancedRouteImport } from './routes/advanced'
import { Route as AcceptRouteImport } from './routes/accept'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPeerjsIndexRouteImport } from './routes/api/peerjs/index'
import { Route as ApiPeerjsIdRouteImport } from './routes/api/peerjs/id'
import { Route as ApiPeerjsKeyPeersRouteImport } from './routes/api/peerjs/$key/peers'

const AdvancedRoute = AdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptRoute = AcceptRouteImport.update({
  id: '/accept',
  path: '/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeerjsIndexRoute = ApiPeerjsIndexRouteImport.update({
  id: '/api/peerjs/',
  path: '/api/peerjs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeerjsIdRoute = ApiPeerjsIdRouteImport.update({
  id: '/api/peerjs/id',
  path: '/api/peerjs/id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeerjsKeyPeersRoute = ApiPeerjsKeyPeersRouteImport.update({
  id: '/api/peerjs/$key/peers',
  path: '/api/peerjs/$key/peers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept': typeof AcceptRoute
  '/advanced': typeof AdvancedRoute
  '/api/peerjs/id': typeof ApiPeerjsIdRoute
  '/api/peerjs/': typeof ApiPeerjsIndexRoute
  '/api/peerjs/$key/peers': typeof ApiPeerjsKeyPeersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept': typeof AcceptRoute
  '/advanced': typeof AdvancedRoute
  '/api/peerjs/id': typeof ApiPeerjsIdRoute
  '/api/peerjs': typeof ApiPeerjsIndexRoute
  '/api/peerjs/$key/peers': typeof ApiPeerjsKeyPeersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept': typeof AcceptRoute
  '/advanced': typeof AdvancedRoute
  '/api/peerjs/id': typeof ApiPeerjsIdRoute
  '/api/peerjs/': typeof ApiPeerjsIndexRoute
  '/api/peerjs/$key/peers': typeof ApiPeerjsKeyPeersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept'
    | '/advanced'
    | '/api/peerjs/id'
    | '/api/peerjs/'
    | '/api/peerjs/$key/peers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept'
    | '/advanced'
    | '/api/peerjs/id'
    | '/api/peerjs'
    | '/api/peerjs/$key/peers'
  id:
    | '__root__'
    | '/'
    | '/accept'
    | '/advanced'
    | '/api/peerjs/id'
    | '/api/peerjs/'
    | '/api/peerjs/$key/peers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptRoute: typeof AcceptRoute
  AdvancedRoute: typeof AdvancedRoute
  ApiPeerjsIdRoute: typeof ApiPeerjsIdRoute
  ApiPeerjsIndexRoute: typeof ApiPeerjsIndexRoute
  ApiPeerjsKeyPeersRoute: typeof ApiPeerjsKeyPeersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/advanced': {
      id: '/advanced'
      path: '/advanced'
      fullPath: '/advanced'
      preLoaderRoute: typeof AdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept': {
      id: '/accept'
      path: '/accept'
      fullPath: '/accept'
      preLoaderRoute: typeof AcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/peerjs/': {
      id: '/api/peerjs/'
      path: '/api/peerjs'
      fullPath: '/api/peerjs/'
      preLoaderRoute: typeof ApiPeerjsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/peerjs/id': {
      id: '/api/peerjs/id'
      path: '/api/peerjs/id'
      fullPath: '/api/peerjs/id'
      preLoaderRoute: typeof ApiPeerjsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/peerjs/$key/peers': {
      id: '/api/peerjs/$key/peers'
      path: '/api/peerjs/$key/peers'
      fullPath: '/api/peerjs/$key/peers'
      preLoaderRoute: typeof ApiPeerjsKeyPeersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptRoute: AcceptRoute,
  AdvancedRoute: AdvancedRoute,
  ApiPeerjsIdRoute: ApiPeerjsIdRoute,
  ApiPeerjsIndexRoute: ApiPeerjsIndexRoute,
  ApiPeerjsKeyPeersRoute: ApiPeerjsKeyPeersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
