/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as QuickRouteImport } from './routes/quick'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as AcceptRouteImport } from './routes/accept'
import { Route as BenchRouteRouteImport } from './routes/bench/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SavedIndexRouteImport } from './routes/saved.index'
import { Route as BenchIndexRouteImport } from './routes/bench/index'
import { Route as SavedIdRouteImport } from './routes/saved.$id'
import { Route as BenchVerifyRouteImport } from './routes/bench/verify'
import { Route as BenchExchangeRouteImport } from './routes/bench/exchange'
import { Route as BenchAcceptRouteImport } from './routes/bench/accept'
import { Route as ApiPeerjsIndexRouteImport } from './routes/api/peerjs/index'
import { Route as ApiJobsIndexRouteImport } from './routes/api/jobs/index'
import { Route as ApiPeerjsIdRouteImport } from './routes/api/peerjs/id'
import { Route as ApiJobsRemotesRouteImport } from './routes/api/jobs/remotes'
import { Route as ApiJobsJobIdIndexRouteImport } from './routes/api/jobs/$jobId/index'
import { Route as ApiPeerjsKeyPeersRouteImport } from './routes/api/peerjs/$key/peers'
import { Route as ApiJobsJobIdResultRouteImport } from './routes/api/jobs/$jobId/result'
import { Route as ApiJobsJobIdRecordRouteImport } from './routes/api/jobs/$jobId/record'
import { Route as ApiJobsJobIdKeysRouteImport } from './routes/api/jobs/$jobId/keys'
import { Route as ApiJobsJobIdEventsRouteImport } from './routes/api/jobs/$jobId/events'
import { Route as ApiJobsJobIdCancelRouteImport } from './routes/api/jobs/$jobId/cancel'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickRoute = QuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptRoute = AcceptRouteImport.update({
  id: '/accept',
  path: '/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchRouteRoute = BenchRouteRouteImport.update({
  id: '/bench',
  path: '/bench',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedIndexRoute = SavedIndexRouteImport.update({
  id: '/saved/',
  path: '/saved/',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchIndexRoute = BenchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BenchRouteRoute,
} as any)
const SavedIdRoute = SavedIdRouteImport.update({
  id: '/saved/$id',
  path: '/saved/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchVerifyRoute = BenchVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => BenchRouteRoute,
} as any)
const BenchExchangeRoute = BenchExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => BenchRouteRoute,
} as any)
const BenchAcceptRoute = BenchAcceptRouteImport.update({
  id: '/accept',
  path: '/accept',
  getParentRoute: () => BenchRouteRoute,
} as any)
const ApiPeerjsIndexRoute = ApiPeerjsIndexRouteImport.update({
  id: '/api/peerjs/',
  path: '/api/peerjs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIndexRoute = ApiJobsIndexRouteImport.update({
  id: '/api/jobs/',
  path: '/api/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeerjsIdRoute = ApiPeerjsIdRouteImport.update({
  id: '/api/peerjs/id',
  path: '/api/peerjs/id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRemotesRoute = ApiJobsRemotesRouteImport.update({
  id: '/api/jobs/remotes',
  path: '/api/jobs/remotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsJobIdIndexRoute = ApiJobsJobIdIndexRouteImport.update({
  id: '/api/jobs/$jobId/',
  path: '/api/jobs/$jobId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeerjsKeyPeersRoute = ApiPeerjsKeyPeersRouteImport.update({
  id: '/api/peerjs/$key/peers',
  path: '/api/peerjs/$key/peers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsJobIdResultRoute = ApiJobsJobIdResultRouteImport.update({
  id: '/api/jobs/$jobId/result',
  path: '/api/jobs/$jobId/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsJobIdRecordRoute = ApiJobsJobIdRecordRouteImport.update({
  id: '/api/jobs/$jobId/record',
  path: '/api/jobs/$jobId/record',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsJobIdKeysRoute = ApiJobsJobIdKeysRouteImport.update({
  id: '/api/jobs/$jobId/keys',
  path: '/api/jobs/$jobId/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsJobIdEventsRoute = ApiJobsJobIdEventsRouteImport.update({
  id: '/api/jobs/$jobId/events',
  path: '/api/jobs/$jobId/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsJobIdCancelRoute = ApiJobsJobIdCancelRouteImport.update({
  id: '/api/jobs/$jobId/cancel',
  path: '/api/jobs/$jobId/cancel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bench': typeof BenchRouteRouteWithChildren
  '/accept': typeof AcceptRoute
  '/exchange': typeof ExchangeRoute
  '/quick': typeof QuickRoute
  '/verify': typeof VerifyRoute
  '/bench/accept': typeof BenchAcceptRoute
  '/bench/exchange': typeof BenchExchangeRoute
  '/bench/verify': typeof BenchVerifyRoute
  '/saved/$id': typeof SavedIdRoute
  '/bench/': typeof BenchIndexRoute
  '/saved/': typeof SavedIndexRoute
  '/api/jobs/remotes': typeof ApiJobsRemotesRoute
  '/api/peerjs/id': typeof ApiPeerjsIdRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/api/peerjs/': typeof ApiPeerjsIndexRoute
  '/api/jobs/$jobId/cancel': typeof ApiJobsJobIdCancelRoute
  '/api/jobs/$jobId/events': typeof ApiJobsJobIdEventsRoute
  '/api/jobs/$jobId/keys': typeof ApiJobsJobIdKeysRoute
  '/api/jobs/$jobId/record': typeof ApiJobsJobIdRecordRoute
  '/api/jobs/$jobId/result': typeof ApiJobsJobIdResultRoute
  '/api/peerjs/$key/peers': typeof ApiPeerjsKeyPeersRoute
  '/api/jobs/$jobId/': typeof ApiJobsJobIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept': typeof AcceptRoute
  '/exchange': typeof ExchangeRoute
  '/quick': typeof QuickRoute
  '/verify': typeof VerifyRoute
  '/bench/accept': typeof BenchAcceptRoute
  '/bench/exchange': typeof BenchExchangeRoute
  '/bench/verify': typeof BenchVerifyRoute
  '/saved/$id': typeof SavedIdRoute
  '/bench': typeof BenchIndexRoute
  '/saved': typeof SavedIndexRoute
  '/api/jobs/remotes': typeof ApiJobsRemotesRoute
  '/api/peerjs/id': typeof ApiPeerjsIdRoute
  '/api/jobs': typeof ApiJobsIndexRoute
  '/api/peerjs': typeof ApiPeerjsIndexRoute
  '/api/jobs/$jobId/cancel': typeof ApiJobsJobIdCancelRoute
  '/api/jobs/$jobId/events': typeof ApiJobsJobIdEventsRoute
  '/api/jobs/$jobId/keys': typeof ApiJobsJobIdKeysRoute
  '/api/jobs/$jobId/record': typeof ApiJobsJobIdRecordRoute
  '/api/jobs/$jobId/result': typeof ApiJobsJobIdResultRoute
  '/api/peerjs/$key/peers': typeof ApiPeerjsKeyPeersRoute
  '/api/jobs/$jobId': typeof ApiJobsJobIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bench': typeof BenchRouteRouteWithChildren
  '/accept': typeof AcceptRoute
  '/exchange': typeof ExchangeRoute
  '/quick': typeof QuickRoute
  '/verify': typeof VerifyRoute
  '/bench/accept': typeof BenchAcceptRoute
  '/bench/exchange': typeof BenchExchangeRoute
  '/bench/verify': typeof BenchVerifyRoute
  '/saved/$id': typeof SavedIdRoute
  '/bench/': typeof BenchIndexRoute
  '/saved/': typeof SavedIndexRoute
  '/api/jobs/remotes': typeof ApiJobsRemotesRoute
  '/api/peerjs/id': typeof ApiPeerjsIdRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/api/peerjs/': typeof ApiPeerjsIndexRoute
  '/api/jobs/$jobId/cancel': typeof ApiJobsJobIdCancelRoute
  '/api/jobs/$jobId/events': typeof ApiJobsJobIdEventsRoute
  '/api/jobs/$jobId/keys': typeof ApiJobsJobIdKeysRoute
  '/api/jobs/$jobId/record': typeof ApiJobsJobIdRecordRoute
  '/api/jobs/$jobId/result': typeof ApiJobsJobIdResultRoute
  '/api/peerjs/$key/peers': typeof ApiPeerjsKeyPeersRoute
  '/api/jobs/$jobId/': typeof ApiJobsJobIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bench'
    | '/accept'
    | '/exchange'
    | '/quick'
    | '/verify'
    | '/bench/accept'
    | '/bench/exchange'
    | '/bench/verify'
    | '/saved/$id'
    | '/bench/'
    | '/saved/'
    | '/api/jobs/remotes'
    | '/api/peerjs/id'
    | '/api/jobs/'
    | '/api/peerjs/'
    | '/api/jobs/$jobId/cancel'
    | '/api/jobs/$jobId/events'
    | '/api/jobs/$jobId/keys'
    | '/api/jobs/$jobId/record'
    | '/api/jobs/$jobId/result'
    | '/api/peerjs/$key/peers'
    | '/api/jobs/$jobId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept'
    | '/exchange'
    | '/quick'
    | '/verify'
    | '/bench/accept'
    | '/bench/exchange'
    | '/bench/verify'
    | '/saved/$id'
    | '/bench'
    | '/saved'
    | '/api/jobs/remotes'
    | '/api/peerjs/id'
    | '/api/jobs'
    | '/api/peerjs'
    | '/api/jobs/$jobId/cancel'
    | '/api/jobs/$jobId/events'
    | '/api/jobs/$jobId/keys'
    | '/api/jobs/$jobId/record'
    | '/api/jobs/$jobId/result'
    | '/api/peerjs/$key/peers'
    | '/api/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/bench'
    | '/accept'
    | '/exchange'
    | '/quick'
    | '/verify'
    | '/bench/accept'
    | '/bench/exchange'
    | '/bench/verify'
    | '/saved/$id'
    | '/bench/'
    | '/saved/'
    | '/api/jobs/remotes'
    | '/api/peerjs/id'
    | '/api/jobs/'
    | '/api/peerjs/'
    | '/api/jobs/$jobId/cancel'
    | '/api/jobs/$jobId/events'
    | '/api/jobs/$jobId/keys'
    | '/api/jobs/$jobId/record'
    | '/api/jobs/$jobId/result'
    | '/api/peerjs/$key/peers'
    | '/api/jobs/$jobId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchRouteRoute: typeof BenchRouteRouteWithChildren
  AcceptRoute: typeof AcceptRoute
  ExchangeRoute: typeof ExchangeRoute
  QuickRoute: typeof QuickRoute
  VerifyRoute: typeof VerifyRoute
  SavedIdRoute: typeof SavedIdRoute
  SavedIndexRoute: typeof SavedIndexRoute
  ApiJobsRemotesRoute: typeof ApiJobsRemotesRoute
  ApiPeerjsIdRoute: typeof ApiPeerjsIdRoute
  ApiJobsIndexRoute: typeof ApiJobsIndexRoute
  ApiPeerjsIndexRoute: typeof ApiPeerjsIndexRoute
  ApiJobsJobIdCancelRoute: typeof ApiJobsJobIdCancelRoute
  ApiJobsJobIdEventsRoute: typeof ApiJobsJobIdEventsRoute
  ApiJobsJobIdKeysRoute: typeof ApiJobsJobIdKeysRoute
  ApiJobsJobIdRecordRoute: typeof ApiJobsJobIdRecordRoute
  ApiJobsJobIdResultRoute: typeof ApiJobsJobIdResultRoute
  ApiPeerjsKeyPeersRoute: typeof ApiPeerjsKeyPeersRoute
  ApiJobsJobIdIndexRoute: typeof ApiJobsJobIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick': {
      id: '/quick'
      path: '/quick'
      fullPath: '/quick'
      preLoaderRoute: typeof QuickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept': {
      id: '/accept'
      path: '/accept'
      fullPath: '/accept'
      preLoaderRoute: typeof AcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench': {
      id: '/bench'
      path: '/bench'
      fullPath: '/bench'
      preLoaderRoute: typeof BenchRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved/': {
      id: '/saved/'
      path: '/saved'
      fullPath: '/saved/'
      preLoaderRoute: typeof SavedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench/': {
      id: '/bench/'
      path: '/'
      fullPath: '/bench/'
      preLoaderRoute: typeof BenchIndexRouteImport
      parentRoute: typeof BenchRouteRoute
    }
    '/saved/$id': {
      id: '/saved/$id'
      path: '/saved/$id'
      fullPath: '/saved/$id'
      preLoaderRoute: typeof SavedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench/verify': {
      id: '/bench/verify'
      path: '/verify'
      fullPath: '/bench/verify'
      preLoaderRoute: typeof BenchVerifyRouteImport
      parentRoute: typeof BenchRouteRoute
    }
    '/bench/exchange': {
      id: '/bench/exchange'
      path: '/exchange'
      fullPath: '/bench/exchange'
      preLoaderRoute: typeof BenchExchangeRouteImport
      parentRoute: typeof BenchRouteRoute
    }
    '/bench/accept': {
      id: '/bench/accept'
      path: '/accept'
      fullPath: '/bench/accept'
      preLoaderRoute: typeof BenchAcceptRouteImport
      parentRoute: typeof BenchRouteRoute
    }
    '/api/peerjs/': {
      id: '/api/peerjs/'
      path: '/api/peerjs'
      fullPath: '/api/peerjs/'
      preLoaderRoute: typeof ApiPeerjsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/': {
      id: '/api/jobs/'
      path: '/api/jobs'
      fullPath: '/api/jobs/'
      preLoaderRoute: typeof ApiJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/peerjs/id': {
      id: '/api/peerjs/id'
      path: '/api/peerjs/id'
      fullPath: '/api/peerjs/id'
      preLoaderRoute: typeof ApiPeerjsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/remotes': {
      id: '/api/jobs/remotes'
      path: '/api/jobs/remotes'
      fullPath: '/api/jobs/remotes'
      preLoaderRoute: typeof ApiJobsRemotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$jobId/': {
      id: '/api/jobs/$jobId/'
      path: '/api/jobs/$jobId'
      fullPath: '/api/jobs/$jobId/'
      preLoaderRoute: typeof ApiJobsJobIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/peerjs/$key/peers': {
      id: '/api/peerjs/$key/peers'
      path: '/api/peerjs/$key/peers'
      fullPath: '/api/peerjs/$key/peers'
      preLoaderRoute: typeof ApiPeerjsKeyPeersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$jobId/result': {
      id: '/api/jobs/$jobId/result'
      path: '/api/jobs/$jobId/result'
      fullPath: '/api/jobs/$jobId/result'
      preLoaderRoute: typeof ApiJobsJobIdResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$jobId/record': {
      id: '/api/jobs/$jobId/record'
      path: '/api/jobs/$jobId/record'
      fullPath: '/api/jobs/$jobId/record'
      preLoaderRoute: typeof ApiJobsJobIdRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$jobId/keys': {
      id: '/api/jobs/$jobId/keys'
      path: '/api/jobs/$jobId/keys'
      fullPath: '/api/jobs/$jobId/keys'
      preLoaderRoute: typeof ApiJobsJobIdKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$jobId/events': {
      id: '/api/jobs/$jobId/events'
      path: '/api/jobs/$jobId/events'
      fullPath: '/api/jobs/$jobId/events'
      preLoaderRoute: typeof ApiJobsJobIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$jobId/cancel': {
      id: '/api/jobs/$jobId/cancel'
      path: '/api/jobs/$jobId/cancel'
      fullPath: '/api/jobs/$jobId/cancel'
      preLoaderRoute: typeof ApiJobsJobIdCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BenchRouteRouteChildren {
  BenchAcceptRoute: typeof BenchAcceptRoute
  BenchExchangeRoute: typeof BenchExchangeRoute
  BenchVerifyRoute: typeof BenchVerifyRoute
  BenchIndexRoute: typeof BenchIndexRoute
}

const BenchRouteRouteChildren: BenchRouteRouteChildren = {
  BenchAcceptRoute: BenchAcceptRoute,
  BenchExchangeRoute: BenchExchangeRoute,
  BenchVerifyRoute: BenchVerifyRoute,
  BenchIndexRoute: BenchIndexRoute,
}

const BenchRouteRouteWithChildren = BenchRouteRoute._addFileChildren(
  BenchRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchRouteRoute: BenchRouteRouteWithChildren,
  AcceptRoute: AcceptRoute,
  ExchangeRoute: ExchangeRoute,
  QuickRoute: QuickRoute,
  VerifyRoute: VerifyRoute,
  SavedIdRoute: SavedIdRoute,
  SavedIndexRoute: SavedIndexRoute,
  ApiJobsRemotesRoute: ApiJobsRemotesRoute,
  ApiPeerjsIdRoute: ApiPeerjsIdRoute,
  ApiJobsIndexRoute: ApiJobsIndexRoute,
  ApiPeerjsIndexRoute: ApiPeerjsIndexRoute,
  ApiJobsJobIdCancelRoute: ApiJobsJobIdCancelRoute,
  ApiJobsJobIdEventsRoute: ApiJobsJobIdEventsRoute,
  ApiJobsJobIdKeysRoute: ApiJobsJobIdKeysRoute,
  ApiJobsJobIdRecordRoute: ApiJobsJobIdRecordRoute,
  ApiJobsJobIdResultRoute: ApiJobsJobIdResultRoute,
  ApiPeerjsKeyPeersRoute: ApiPeerjsKeyPeersRoute,
  ApiJobsJobIdIndexRoute: ApiJobsJobIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
