import { spawn } from "node:child_process";
import { existsSync } from "node:fs";
import { Socket } from "node:net";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { sftpPort } from "./env";

// Vitest globalSetup for the `integration` project: brings the SFTP test
// container up before the suite and tears it down after, so `npm run
// test:integration` is self-contained rather than requiring the operator to run
// test:container:up / :down by hand. Only the integration project references
// this file, so the unit project (and `npm run test`) never touches Docker.
//
// The manual test:container:* scripts are still useful for keeping a warm
// container across many runs; this hook detects an already-running container and
// reuses it (leaving it up on teardown) so that workflow keeps working.

const here = dirname(fileURLToPath(import.meta.url));
// apps/cli/test/container -> repo root is four levels up. docker compose must
// run from the repo root because compose.yaml interpolates ${PWD} into its
// bind-mount paths, so PWD has to be the root for the mounts to resolve. The npm
// test:container:* scripts get this with `cd $(git rev-parse --show-toplevel)`.
const repoRoot = resolve(here, "../../../..");
const CONTAINER_DIR = resolve(repoRoot, "apps/cli/test/container");
// Repo-root-relative, matching the test:container:* scripts so both paths agree.
const ENV_FILE = "apps/cli/test/container/.env";
const COMPOSE_FILE = "apps/cli/test/container/compose.yaml";
const SETUP_SCRIPT = "apps/cli/test/container/setup.sh";
// A host key generated by setup.sh; its absence means setup.sh has not run in
// this checkout yet (host keys, srv dir, and .env are all gitignored).
const HOST_KEY = resolve(CONTAINER_DIR, "sftp/ssh_host_ed25519_key");

// sshd accepting a TCP connection is sufficient readiness for the SFTP client
// to open. The window this guards is between `up` returning ("running") and
// sshd actually listening, which is where a naive `up`-then-connect races.
const READY_TIMEOUT_MS = 60_000;
const READY_PROBE_INTERVAL_MS = 250;
// Short probe to detect a container that is already up (a manual
// test:container:up, or a warm one from a prior run) so we reuse rather than
// recreate it -- and, crucially, leave it running on teardown.
const REUSE_PROBE_TIMEOUT_MS = 500;

// Runs a command from the repo root, capturing stderr for diagnostics. PWD is
// set explicitly because child_process does not update it when `cwd` is set, and
// compose.yaml reads ${PWD} for its bind-mount paths.
function run(
  cmd: string,
  args: string[],
): Promise<{ code: number; stderr: string }> {
  return new Promise((resolveRun, reject) => {
    const child = spawn(cmd, args, {
      cwd: repoRoot,
      env: { ...process.env, PWD: repoRoot },
    });
    let stderr = "";
    child.stderr?.on("data", (chunk) => (stderr += String(chunk)));
    child.on("error", (err: NodeJS.ErrnoException) => {
      if (cmd === "docker" && err.code === "ENOENT")
        reject(
          new Error(
            "Docker is required for the CLI integration tests but `docker` " +
              "was not found on PATH.",
          ),
        );
      else reject(err);
    });
    child.on("close", (code) => resolveRun({ code: code ?? 0, stderr }));
  });
}

const compose = (...args: string[]) =>
  run("docker", [
    "compose",
    "--env-file",
    ENV_FILE,
    "-f",
    COMPOSE_FILE,
    ...args,
  ]);

// Resolves true if a TCP connection to localhost:port is accepted within
// timeoutMs, false on refusal/timeout. Used both to detect an already-running
// container and to wait for sshd after starting one.
function portAccepts(port: number, timeoutMs: number): Promise<boolean> {
  return new Promise((resolveProbe) => {
    const socket = new Socket();
    const settle = (ok: boolean) => {
      socket.destroy();
      resolveProbe(ok);
    };
    socket.setTimeout(timeoutMs);
    socket.once("connect", () => settle(true));
    socket.once("timeout", () => settle(false));
    socket.once("error", () => settle(false));
    socket.connect(port, "127.0.0.1");
  });
}

async function waitForPort(port: number): Promise<void> {
  const deadline = Date.now() + READY_TIMEOUT_MS;
  for (;;) {
    if (await portAccepts(port, READY_PROBE_INTERVAL_MS)) return;
    if (Date.now() >= deadline)
      throw new Error(
        `SFTP test container did not accept connections on port ${port} ` +
          `within ${READY_TIMEOUT_MS / 1000}s. Inspect it with: ` +
          `docker compose --env-file ${ENV_FILE} -f ${COMPOSE_FILE} logs`,
      );
    await new Promise((r) => setTimeout(r, READY_PROBE_INTERVAL_MS));
  }
}

// Generates the gitignored host keys, srv dir, and .env on a fresh checkout that
// has not run setup.sh. setup.sh is idempotent (ssh-keygen declines to overwrite
// an existing key given EOF on stdin, and .env is written only when absent), so
// this neither clobbers existing keys nor a worktree's per-checkout port.
async function ensureArtifacts(): Promise<void> {
  if (existsSync(HOST_KEY)) return;
  console.log("[sftp-container] generating host keys and .env via setup.sh");
  const { code, stderr } = await run("sh", [SETUP_SCRIPT]);
  if (code !== 0)
    throw new Error(`container setup.sh failed (exit ${code}): ${stderr}`);
}

export default async function setup(): Promise<() => Promise<void>> {
  const port = sftpPort();

  // Reuse a container that is already serving the port (manual warm container or
  // a leftover from a prior run): skip bring-up and leave it on teardown, so the
  // test:container:up / :down workflow this hook complements keeps working.
  if (await portAccepts(port, REUSE_PROBE_TIMEOUT_MS)) {
    console.log(
      `[sftp-container] reusing container already listening on port ${port}`,
    );
    return async () => {};
  }

  await ensureArtifacts();

  console.log(`[sftp-container] starting SFTP test container on port ${port}`);
  // Self-healing: down --remove-orphans first clears any leftover from an
  // interrupted run -- in particular a half-created, port-less container that a
  // bare `up` would otherwise just restart without its port mapping. Failures
  // are ignored; there may be nothing to remove.
  await compose("down", "--remove-orphans");

  const up = await compose("up", "-d");
  if (up.code !== 0)
    throw new Error(
      `\`docker compose up\` for the SFTP test container failed (exit ` +
        `${up.code}). If the port is already allocated, another container may ` +
        `be holding it; stop it or set SFTP_PORT to a free port.\n${up.stderr}`,
    );

  try {
    await waitForPort(port);
  } catch (err) {
    // Do not leave a started-but-unready container behind.
    await compose("down").catch(() => {});
    throw err;
  }
  console.log(`[sftp-container] ready on port ${port}`);

  return async () => {
    console.log("[sftp-container] stopping SFTP test container");
    await compose("down");
  };
}
