import { z } from "zod";

import {
  LinkageTermsSchema,
  SHARED_SECRET_REGEX,
  mintExchangeFile,
} from "@psilink/core";

import type {
  ExchangeFileInput,
  FileSyncOptions,
  LinkageTerms,
} from "@psilink/core";

/**
 * The tuning knobs a client may set on a job. Deliberately the numeric/boolean
 * subset of the CLI's file-sync options: every field here is a number, a
 * boolean, or a closed enum, so none can carry a path, host, credential, or
 * command. Path and directory fields of {@link FileSyncOptions} are intentionally
 * NOT surfaced -- the server owns every directory. `peerId` (a free-text field)
 * is omitted for the same reason.
 */
export interface JobExchangeOptions {
  pollIntervalMs?: number;
  peerTimeoutMs?: number;
  serverConnectTimeoutMs?: number;
  maxReconnectAttempts?: number;
  timestampInFilename?: boolean;
  locklessRendezvous?: boolean;
  retainFiles?: boolean;
  unexpectedFiles?: "error" | "warn" | "ignore";
}

const jobExchangeOptionsSchema: z.ZodType<JobExchangeOptions> = z
  .object({
    pollIntervalMs: z.number().int().positive().optional(),
    peerTimeoutMs: z.number().int().positive().optional(),
    serverConnectTimeoutMs: z.number().int().positive().optional(),
    maxReconnectAttempts: z.number().int().min(0).max(604800).optional(),
    timestampInFilename: z.boolean().optional(),
    locklessRendezvous: z.boolean().optional(),
    retainFiles: z.boolean().optional(),
    unexpectedFiles: z.enum(["error", "warn", "ignore"]).optional(),
  })
  .strict();

/**
 * The typed, schema-validated intent a client submits to create a job. It is the
 * ONLY channel from the client into a CLI invocation, and it is injection-closed
 * by construction:
 *
 * - `channel` is a closed enum; only `filedrop` is accepted for this cut. A
 *   filedrop exchange has no host and no credentials at all, so the connection
 *   block the server composes carries no injectable field.
 * - `linkageTerms` is validated by core's {@link LinkageTermsSchema}, whose
 *   vocabulary is bounded partner-authored text (field names, key elements,
 *   transforms) -- it carries no filesystem path, host, or command field, so a
 *   hostile value cannot escape into argv or the filesystem.
 * - `sharedSecret` is credential material matching the CLI key-file shape; it is
 *   written into a fixed-name key file, never used as a path or argv fragment.
 * - `inputCsv` is CONTENT the server writes to a fixed, server-chosen filename in
 *   the job workdir; the client never names a file.
 * - `options` is the numeric/boolean/enum subset of the CLI's tuning options.
 *
 * Every directory the exchange uses is generated by the server inside the job
 * workdir; the intent cannot name one. There is no field here that becomes a
 * path, a host, a credential reference (`@path`), or an argv string.
 */
export interface JobExchangeIntent {
  channel: "filedrop";
  linkageTerms: LinkageTerms;
  sharedSecret: string;
  inputCsv: string;
  options?: JobExchangeOptions;
  eventStream?: boolean;
}

/**
 * Zod schema for {@link JobExchangeIntent}. `.strict()` rejects any unknown key,
 * so a client cannot smuggle an unmodeled field (a `path`, a `host`, an
 * `@path` credential) past validation. The `channel` enum admits only
 * `filedrop`; an `sftp` or `webrtc` intent is rejected as an unknown intent
 * rather than silently accepted, keeping the injection surface to the one
 * credential-free channel.
 */
export const jobExchangeIntentSchema: z.ZodType<JobExchangeIntent> = z
  .object({
    channel: z.literal("filedrop"),
    linkageTerms: LinkageTermsSchema,
    sharedSecret: z
      .string()
      .regex(
        SHARED_SECRET_REGEX,
        "sharedSecret must be a base64url-encoded 32-byte value (43 base64url characters)",
      ),
    inputCsv: z.string().min(1),
    options: jobExchangeOptionsSchema.optional(),
    eventStream: z.boolean().optional(),
  })
  .strict();

/**
 * The fixed, server-chosen file names inside a job workdir. The client never
 * supplies a filename: content it submits is written to these names, and the CLI
 * is pointed at them. Keeping them constant is what makes "a client string never
 * becomes a file path" hold.
 */
export const JOB_FILE_NAMES = {
  /** The composed CLI config document. */
  config: "psilink.yaml",
  /** The CLI key file carrying the shared secret. */
  key: ".psilink.key",
  /** The client's input CSV content. */
  input: "input.csv",
  /** The rendezvous directory the filedrop exchange reads and writes. */
  exchangeDirectory: "exchange",
  /** The CLI's matched-result output. */
  output: "output.csv",
} as const;

/**
 * Compose the CLI config document (snake_case YAML the CLI loads verbatim) from a
 * validated {@link JobExchangeIntent}, overriding the connection directory to the
 * server-chosen `exchangeDirectoryPath` inside the job workdir.
 *
 * The connection is built as a credential-free filedrop locator, so by core's
 * {@link ExchangeFileInput} typing no credential is representable; `mintExchangeFile`
 * validates the assembled spec through the CLI's own schema and never assembles
 * an `authentication` block (the shared secret rides the key file). The client's
 * `linkageTerms` reach the file only after core's schema validation, and the one
 * path field (`path`) is set by the server, not the client.
 */
export function composeConfigDocument(
  intent: JobExchangeIntent,
  exchangeDirectoryPath: string,
): string {
  const options = intentOptionsToFileSyncOptions(intent.options);
  const fileInput: ExchangeFileInput = {
    connection: {
      channel: "filedrop",
      path: exchangeDirectoryPath,
      ...(options !== undefined ? { options } : {}),
    },
    linkageTerms: intent.linkageTerms,
  };
  return mintExchangeFile(fileInput);
}

/**
 * Serialize the CLI key file body. Only the shared secret is written; no
 * `expires` is stamped, so a server-driven job carries no invitation-token
 * lifetime of its own.
 */
export function composeKeyFileDocument(intent: JobExchangeIntent): string {
  return JSON.stringify({ sharedSecret: intent.sharedSecret });
}

/**
 * Narrow the intent's tuning subset into a {@link FileSyncOptions}. Returns
 * undefined when no option was set, so the composed connection omits the block
 * entirely rather than carrying an empty object.
 */
function intentOptionsToFileSyncOptions(
  options: JobExchangeOptions | undefined,
): FileSyncOptions | undefined {
  if (options === undefined) return undefined;
  const entries = Object.entries(options).filter(
    ([, value]) => value !== undefined,
  );
  if (entries.length === 0) return undefined;
  return Object.fromEntries(entries);
}
