import { z } from "zod";

import {
  LinkageTermsSchema,
  MetadataSchema,
  SHARED_SECRET_REGEX,
  StandardizationSchema,
  mintExchangeFile,
} from "@psilink/core";

import type {
  ExchangeFileInput,
  FileSyncOptions,
  LinkageTerms,
  Metadata,
  Standardization,
} from "@psilink/core";

/**
 * The tuning knobs a client may set on a job. Deliberately the numeric/boolean
 * subset of the CLI's file-sync options: every field here is a number, a
 * boolean, or a closed enum, so none can carry a path, host, credential, or
 * command. Path and directory fields of {@link FileSyncOptions} are intentionally
 * NOT surfaced -- the server owns every directory. `peerId` (a free-text field)
 * is omitted for the same reason.
 */
export interface JobExchangeOptions {
  pollIntervalMs?: number;
  peerTimeoutMs?: number;
  serverConnectTimeoutMs?: number;
  maxReconnectAttempts?: number;
  timestampInFilename?: boolean;
  locklessRendezvous?: boolean;
  retainFiles?: boolean;
  unexpectedFiles?: "error" | "warn" | "ignore";
}

const jobExchangeOptionsSchema: z.ZodType<JobExchangeOptions> = z
  .object({
    pollIntervalMs: z.number().int().positive().optional(),
    peerTimeoutMs: z.number().int().positive().optional(),
    serverConnectTimeoutMs: z.number().int().positive().optional(),
    maxReconnectAttempts: z.number().int().min(0).max(604800).optional(),
    timestampInFilename: z.boolean().optional(),
    locklessRendezvous: z.boolean().optional(),
    retainFiles: z.boolean().optional(),
    unexpectedFiles: z.enum(["error", "warn", "ignore"]).optional(),
  })
  .strict();

/**
 * The typed, schema-validated intent a client submits to create a job. It is the
 * ONLY channel from the client into a CLI invocation, and it is injection-closed
 * by construction:
 *
 * - `channel` is a closed enum; only `filedrop` is accepted for this cut. A
 *   filedrop exchange has no host and no credentials at all, so the connection
 *   block the server composes carries no injectable field.
 * - `linkageTerms` is validated by core's {@link LinkageTermsSchema}, whose
 *   vocabulary is bounded partner-authored text (field names, key elements,
 *   transforms) -- it carries no filesystem path, host, or command field, so a
 *   hostile value cannot escape into argv or the filesystem.
 * - `sharedSecret` is credential material matching the CLI key-file shape; it is
 *   written into a fixed-name key file, never used as a path or argv fragment.
 * - `inputCsv` is CONTENT the server writes to a fixed, server-chosen filename in
 *   the job workdir; the client never names a file.
 * - `options` is the numeric/boolean/enum subset of the CLI's tuning options.
 * - `metadata` and `standardization` are the operator's per-party data-prep edits
 *   (which columns are sent vs ignored, their roles/types, and the transform
 *   pipeline). Both are validated structured data -- core's {@link MetadataSchema}
 *   and {@link StandardizationSchema} -- carrying only column names/roles/types and
 *   a step pipeline. They are written into the composed config as YAML VALUES, never
 *   as an argv fragment, a path, a host, or a credential. The connection block the
 *   server composes is unaffected by them, so neither can redirect a directory or
 *   introduce an authentication field. Note the size bound is only partial: each
 *   column `name` is length-capped and `role`/`type` are closed enums, but the
 *   metadata/standardization ARRAYS and the free-text `description`, `output`,
 *   `input`, and standardization `params` are not length-bounded by these schemas.
 *   The linkage-terms dialect gate (which caps and dialect-checks transform-pattern
 *   SOURCES) applies to `linkageTerms` patterns, not to the standardization
 *   pipeline's raw-pattern steps -- so a client can submit a large or (in the
 *   linkage-terms sense) non-conformant `standardization` pattern. That is a
 *   compile/size cost, NOT a ReDoS hole: every standardization raw-pattern step
 *   still compiles and runs under core's linear-time RE2 engine (RE2JS), so it
 *   cannot backtrack catastrophically. It stays a resource bound, not an injection
 *   escape: it cannot become argv/path/host/credential.
 * - `expectedPayloadColumns` is the acceptor's received-payload lock-in: a list of
 *   partner-namespace column names, no path/host/credential. See the field doc for
 *   the empty-vs-absent semantics.
 *
 * Every directory the exchange uses is generated by the server inside the job
 * workdir; the intent cannot name one. There is no field here that becomes a
 * path, a host, a credential reference (`@path`), or an argv string.
 */
export interface JobExchangeIntent {
  channel: "filedrop";
  linkageTerms: LinkageTerms;
  sharedSecret: string;
  inputCsv: string;
  metadata?: Metadata;
  standardization?: Standardization;
  /**
   * The acceptor's RECEIVE-side lock-in: the partner-namespace columns this party
   * will enforce it receives (the invitation's disclosed set). Mirrors the browser
   * acceptor, which sets `prepared.expectedPayloadColumns` from the same source so
   * an inviter that sends extra columns aborts the exchange rather than having them
   * silently ingested. Column names only -- never a path, host, or credential.
   *
   * The empty-vs-absent distinction is load-bearing: an empty array is a strict
   * "receive nothing" (a non-empty partner payload then aborts), while an omitted
   * field reconciles lazily. It is forwarded (below) whenever it is present,
   * INCLUDING an empty array, so the strict form is preserved.
   */
  expectedPayloadColumns?: Array<string>;
  options?: JobExchangeOptions;
  eventStream?: boolean;
}

/**
 * Zod schema for {@link JobExchangeIntent}. `.strict()` rejects any unknown key,
 * so a client cannot smuggle an unmodeled field (a `path`, a `host`, an
 * `@path` credential) past validation. The `channel` enum admits only
 * `filedrop`; an `sftp` or `webrtc` intent is rejected as an unknown intent
 * rather than silently accepted, keeping the injection surface to the one
 * credential-free channel.
 */
export const jobExchangeIntentSchema: z.ZodType<JobExchangeIntent> = z
  .object({
    channel: z.literal("filedrop"),
    linkageTerms: LinkageTermsSchema,
    sharedSecret: z
      .string()
      .regex(
        SHARED_SECRET_REGEX,
        "sharedSecret must be a base64url-encoded 32-byte value (43 base64url characters)",
      ),
    inputCsv: z.string().min(1),
    metadata: MetadataSchema.optional(),
    standardization: StandardizationSchema.optional(),
    expectedPayloadColumns: z.array(z.string()).optional(),
    options: jobExchangeOptionsSchema.optional(),
    eventStream: z.boolean().optional(),
  })
  .strict();

/**
 * The fixed, server-chosen file names inside a job workdir. The client never
 * supplies a filename: content it submits is written to these names, and the CLI
 * is pointed at them. Keeping them constant is what makes "a client string never
 * becomes a file path" hold.
 */
export const JOB_FILE_NAMES = {
  /** The composed CLI config document. */
  config: "psilink.yaml",
  /** The CLI key file carrying the shared secret. */
  key: ".psilink.key",
  /** The client's input CSV content. */
  input: "input.csv",
  /** The rendezvous directory the filedrop exchange reads and writes. */
  exchangeDirectory: "exchange",
  /** The CLI's matched-result output. */
  output: "output.csv",
  /** The self-attested exchange record, pinned so the server knows its path
   * (the CLI's `--record-file` target). */
  record: "record.json",
  /** The private verification keys paired with {@link JOB_FILE_NAMES.record}.
   * Must equal the CLI's `keysPathFor` derivation of the record name (`.json` ->
   * `.keys.json`); a unit test pins this cross-workspace pairing. */
  recordKeys: "record.keys.json",
} as const;

/**
 * Compose the CLI config document (snake_case YAML the CLI loads verbatim) from a
 * validated {@link JobExchangeIntent}, overriding the connection directory to the
 * server-chosen `exchangeDirectoryPath` inside the job workdir.
 *
 * The connection is built as a credential-free filedrop locator, so by core's
 * {@link ExchangeFileInput} typing no credential is representable; `mintExchangeFile`
 * validates the assembled spec through the CLI's own schema and never assembles
 * an `authentication` block (the shared secret rides the key file). The client's
 * `linkageTerms`, and its `metadata`/`standardization` when present, reach the file
 * only after core's schema validation, and the one path field (`path`) is set by
 * the server, not the client.
 *
 * Forwarding `metadata`/`standardization` is what makes the operator's data-prep
 * edits authoritative on the console path: the CLI's `prepareForExchange` uses the
 * composed metadata rather than falling back to `inferMetadata`, so a column the
 * operator marked ignored (or non-payload) is not silently disclosed.
 *
 * `expectedPayloadColumns`, when present, is forwarded as the config's
 * `expected_payload_columns` so the acceptor's received-payload lock-in is
 * enforced explicitly (the CLI prefers it over the `payload.receive` fallback);
 * an empty array is forwarded verbatim -- it means "receive nothing" and must lock
 * in strictly -- and only an omitted field reconciles lazily.
 */
export function composeConfigDocument(
  intent: JobExchangeIntent,
  exchangeDirectoryPath: string,
): string {
  const options = intentOptionsToFileSyncOptions(intent.options);
  const { metadata, standardization, expectedPayloadColumns } = intent;
  const fileInput: ExchangeFileInput = {
    connection: {
      channel: "filedrop",
      path: exchangeDirectoryPath,
      ...(options !== undefined ? { options } : {}),
    },
    linkageTerms: intent.linkageTerms,
    ...(metadata !== undefined ? { metadata } : {}),
    ...(standardization !== undefined ? { standardization } : {}),
    ...(expectedPayloadColumns !== undefined ? { expectedPayloadColumns } : {}),
  };
  return mintExchangeFile(fileInput);
}

/**
 * Serialize the CLI key file body. Only the shared secret is written; no
 * `expires` is stamped, so a server-driven job carries no invitation-token
 * lifetime of its own.
 */
export function composeKeyFileDocument(intent: JobExchangeIntent): string {
  return JSON.stringify({ sharedSecret: intent.sharedSecret });
}

/**
 * Narrow the intent's tuning subset into a {@link FileSyncOptions}. Returns
 * undefined when no option was set, so the composed connection omits the block
 * entirely rather than carrying an empty object.
 */
function intentOptionsToFileSyncOptions(
  options: JobExchangeOptions | undefined,
): FileSyncOptions | undefined {
  if (options === undefined) return undefined;
  const entries = Object.entries(options).filter(
    ([, value]) => value !== undefined,
  );
  if (entries.length === 0) return undefined;
  return Object.fromEntries(entries);
}
