// @ts-ignore this is really there
import PSI from "@openmined/psi.js/psi_wasm_worker";

import { loadPsiBackend, servePsiWorker } from "@psilink/core";

import {
  createBufferingRequestRouter,
  decodePsiWorkerInit,
} from "./psiCryptoController";

import type { PsiWorkerRequest, PsiWorkerResponse } from "@psilink/core";
import type { PSILibrary } from "@openmined/psi.js/implementation/psi.d.ts";

/**
 * The off-main-thread PSI crypto worker. It runs core's `servePsiWorker` dispatcher
 * over a freshly loaded WASM engine, so the elliptic-curve masking a PSI round
 * performs runs here instead of on the browser's UI thread -- keeping the tab
 * interactive and the WebRTC peer keepalives firing during a round (board item
 * 209368277). Bundled by Vite from {@link ./psiCryptoWorkerClient}; the WASM worker
 * build (`@openmined/psi.js/psi_wasm_worker`) is the worker-context sibling of the
 * `psi_wasm_web` entry the main thread loads. The secret key is generated by
 * `createWithNewKey` inside `servePsiWorker` and never leaves this worker.
 *
 * The buffer / drain / load-failure coordination lives in
 * {@link createBufferingRequestRouter} (Node-unit-tested); this entry only wires the
 * worker globals to it.
 */

// Worker globals are not in the app's DOM lib; narrow `globalThis` to the
// dedicated-worker affordances this entry uses (its role/id seed on `self.name`, the
// inbound request channel, and the outbound reply post) rather than pulling the
// WebWorker lib into the whole program (which would clash with DOM on
// `self`/`postMessage`).
interface WorkerScope {
  name: string;
  onmessage: ((event: { data: PsiWorkerRequest }) => void) | null;
  postMessage: (message: PsiWorkerResponse) => void;
}
const scope = globalThis as unknown as WorkerScope;

// `onmessage` is attached synchronously at module top (below), before the async engine
// load yields, so a request the host posts before this worker script finishes running
// is not lost: the platform holds any already-posted message until the synchronous
// top-level completes and the listener exists. The router then buffers any request
// arriving during the SEPARATE window -- after the listener exists but before the async
// WASM load has made the dispatcher ready -- and drains it in order once the engine
// loads (or fails it fast if the load fails).
const onRequest = createBufferingRequestRouter(
  async () => {
    // The role/id seed rides self.name (set at construction), the browser analogue of
    // the CLI worker's workerData -- available synchronously at startup. The browser
    // always uses WASM; loadPsiBackend keeps the backend selection identical to the
    // main-thread path (ExchangeView), which has no native addon.
    const init = decodePsiWorkerInit(scope.name);
    const { library } = await loadPsiBackend(
      { loadWasm: () => PSI() as Promise<PSILibrary> },
      { isNode: false },
    );
    return servePsiWorker(library, init, (response: PsiWorkerResponse) =>
      scope.postMessage(response),
    );
  },
  (id, error) => scope.postMessage({ id, ok: false, error }),
);

scope.onmessage = (event) => onRequest(event.data);
