// @ts-ignore this is really there
import PSI from "@openmined/psi.js/psi_wasm_worker";

import { loadPsiBackend, servePsiWorker } from "@psilink/core";

import { decodePsiWorkerInit } from "./psiCryptoController";

import type { PsiWorkerRequest, PsiWorkerResponse } from "@psilink/core";
import type { PSILibrary } from "@openmined/psi.js/implementation/psi.d.ts";

/**
 * The off-main-thread PSI crypto worker. It runs core's `servePsiWorker` dispatcher
 * over a freshly loaded WASM engine, so the elliptic-curve masking a PSI round
 * performs runs here instead of on the browser's UI thread -- keeping the tab
 * interactive and the WebRTC peer keepalives firing during a round (board item
 * 209368277). Bundled by Vite from {@link ./psiCryptoWorkerClient}; the WASM worker
 * build (`@openmined/psi.js/psi_wasm_worker`) is the worker-context sibling of the
 * `psi_wasm_web` entry the main thread loads. The secret key is generated by
 * `createWithNewKey` inside `servePsiWorker` and never leaves this worker.
 */

// Worker globals are not in the app's DOM lib; narrow `globalThis` to the
// dedicated-worker affordances this entry uses (its role/id seed on `self.name`, the
// inbound request channel, and the outbound reply post) rather than pulling the
// WebWorker lib into the whole program (which would clash with DOM on
// `self`/`postMessage`).
interface WorkerScope {
  name: string;
  onmessage: ((event: { data: PsiWorkerRequest }) => void) | null;
  postMessage: (message: PsiWorkerResponse) => void;
}
const scope = globalThis as unknown as WorkerScope;

// The dispatcher, ready once the WASM backend loads. Requests that arrive during the
// async load are buffered here and drained in order once it is ready. onmessage is
// attached SYNCHRONOUSLY below (before the async load yields), so no request is
// missed: a DedicatedWorkerGlobalScope fires `message` events immediately, so unlike
// the CLI worker (whose `worker_threads` port buffers until a listener attaches) this
// side cannot rely on the platform to queue messages posted before the dispatcher
// exists -- it buffers them itself.
let dispatch: ((request: PsiWorkerRequest) => void) | undefined;
const buffered: Array<PsiWorkerRequest> = [];
// Set to the load failure's message once the backend cannot load; every buffered and
// subsequent request is then answered with it (see below), so the host's pending
// crypto call fails fast rather than hanging on a worker that will never reply --
// the browser counterpart of the CLI worker's exit(1)-on-load-failure signal.
let loadFailure: string | undefined;

async function start(): Promise<void> {
  // The role/id seed rides self.name (set at construction), the browser analogue of
  // the CLI worker's workerData -- available synchronously at startup.
  const init = decodePsiWorkerInit(scope.name);
  // The browser always uses WASM; loadPsiBackend keeps the backend selection
  // identical to the main-thread path (ExchangeView), which has no native addon.
  const { library } = await loadPsiBackend(
    { loadWasm: () => PSI() as Promise<PSILibrary> },
    { isNode: false },
  );
  const ready = servePsiWorker(library, init, (response: PsiWorkerResponse) =>
    scope.postMessage(response),
  );
  for (const request of buffered) ready(request);
  buffered.length = 0;
  dispatch = ready;
}

scope.onmessage = (event) => {
  const request = event.data;
  if (loadFailure !== undefined) {
    scope.postMessage({ id: request.id, ok: false, error: loadFailure });
    return;
  }
  if (dispatch) dispatch(request);
  else buffered.push(request);
};

void start().catch((error: unknown) => {
  // The WASM backend failed to load; there is nothing to serve. Answer every buffered
  // request -- and, via the flag, every later one -- with the failure so the host's
  // pending call rejects rather than hanging on a reply that will never come.
  loadFailure = error instanceof Error ? error.message : String(error);
  for (const request of buffered)
    scope.postMessage({ id: request.id, ok: false, error: loadFailure });
  buffered.length = 0;
});
