/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PsiRouteImport } from './routes/psi'
import { Route as IndexRouteImport } from './routes/index'
import { ServerRoute as ApiPeerjsIndexServerRouteImport } from './routes/api/peerjs/index'
import { ServerRoute as ApiPsiCreateServerRouteImport } from './routes/api/psi/create'
import { ServerRoute as ApiPeerjsIdServerRouteImport } from './routes/api/peerjs/id'
import { ServerRoute as ApiPsiIdIndexServerRouteImport } from './routes/api/psi/$id/index'
import { ServerRoute as ApiPsiIdWaitServerRouteImport } from './routes/api/psi/$id/wait'
import { ServerRoute as ApiPeerjsKeyPeersServerRouteImport } from './routes/api/peerjs/$key/peers'

const rootServerRouteImport = createServerRootRoute()

const PsiRoute = PsiRouteImport.update({
  id: '/psi',
  path: '/psi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeerjsIndexServerRoute = ApiPeerjsIndexServerRouteImport.update({
  id: '/api/peerjs/',
  path: '/api/peerjs/',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiPsiCreateServerRoute = ApiPsiCreateServerRouteImport.update({
  id: '/api/psi/create',
  path: '/api/psi/create',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiPeerjsIdServerRoute = ApiPeerjsIdServerRouteImport.update({
  id: '/api/peerjs/id',
  path: '/api/peerjs/id',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiPsiIdIndexServerRoute = ApiPsiIdIndexServerRouteImport.update({
  id: '/api/psi/$id/',
  path: '/api/psi/$id/',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiPsiIdWaitServerRoute = ApiPsiIdWaitServerRouteImport.update({
  id: '/api/psi/$id/wait',
  path: '/api/psi/$id/wait',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiPeerjsKeyPeersServerRoute = ApiPeerjsKeyPeersServerRouteImport.update({
  id: '/api/peerjs/$key/peers',
  path: '/api/peerjs/$key/peers',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/psi': typeof PsiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/psi': typeof PsiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/psi': typeof PsiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/psi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/psi'
  id: '__root__' | '/' | '/psi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PsiRoute: typeof PsiRoute
}
export interface FileServerRoutesByFullPath {
  '/api/peerjs/id': typeof ApiPeerjsIdServerRoute
  '/api/psi/create': typeof ApiPsiCreateServerRoute
  '/api/peerjs': typeof ApiPeerjsIndexServerRoute
  '/api/peerjs/$key/peers': typeof ApiPeerjsKeyPeersServerRoute
  '/api/psi/$id/wait': typeof ApiPsiIdWaitServerRoute
  '/api/psi/$id': typeof ApiPsiIdIndexServerRoute
}
export interface FileServerRoutesByTo {
  '/api/peerjs/id': typeof ApiPeerjsIdServerRoute
  '/api/psi/create': typeof ApiPsiCreateServerRoute
  '/api/peerjs': typeof ApiPeerjsIndexServerRoute
  '/api/peerjs/$key/peers': typeof ApiPeerjsKeyPeersServerRoute
  '/api/psi/$id/wait': typeof ApiPsiIdWaitServerRoute
  '/api/psi/$id': typeof ApiPsiIdIndexServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/peerjs/id': typeof ApiPeerjsIdServerRoute
  '/api/psi/create': typeof ApiPsiCreateServerRoute
  '/api/peerjs/': typeof ApiPeerjsIndexServerRoute
  '/api/peerjs/$key/peers': typeof ApiPeerjsKeyPeersServerRoute
  '/api/psi/$id/wait': typeof ApiPsiIdWaitServerRoute
  '/api/psi/$id/': typeof ApiPsiIdIndexServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/api/peerjs/id'
    | '/api/psi/create'
    | '/api/peerjs'
    | '/api/peerjs/$key/peers'
    | '/api/psi/$id/wait'
    | '/api/psi/$id'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/api/peerjs/id'
    | '/api/psi/create'
    | '/api/peerjs'
    | '/api/peerjs/$key/peers'
    | '/api/psi/$id/wait'
    | '/api/psi/$id'
  id:
    | '__root__'
    | '/api/peerjs/id'
    | '/api/psi/create'
    | '/api/peerjs/'
    | '/api/peerjs/$key/peers'
    | '/api/psi/$id/wait'
    | '/api/psi/$id/'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiPeerjsIdServerRoute: typeof ApiPeerjsIdServerRoute
  ApiPsiCreateServerRoute: typeof ApiPsiCreateServerRoute
  ApiPeerjsIndexServerRoute: typeof ApiPeerjsIndexServerRoute
  ApiPeerjsKeyPeersServerRoute: typeof ApiPeerjsKeyPeersServerRoute
  ApiPsiIdWaitServerRoute: typeof ApiPsiIdWaitServerRoute
  ApiPsiIdIndexServerRoute: typeof ApiPsiIdIndexServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/psi': {
      id: '/psi'
      path: '/psi'
      fullPath: '/psi'
      preLoaderRoute: typeof PsiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/peerjs/': {
      id: '/api/peerjs/'
      path: '/api/peerjs'
      fullPath: '/api/peerjs'
      preLoaderRoute: typeof ApiPeerjsIndexServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/psi/create': {
      id: '/api/psi/create'
      path: '/api/psi/create'
      fullPath: '/api/psi/create'
      preLoaderRoute: typeof ApiPsiCreateServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/peerjs/id': {
      id: '/api/peerjs/id'
      path: '/api/peerjs/id'
      fullPath: '/api/peerjs/id'
      preLoaderRoute: typeof ApiPeerjsIdServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/psi/$id/': {
      id: '/api/psi/$id/'
      path: '/api/psi/$id'
      fullPath: '/api/psi/$id'
      preLoaderRoute: typeof ApiPsiIdIndexServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/psi/$id/wait': {
      id: '/api/psi/$id/wait'
      path: '/api/psi/$id/wait'
      fullPath: '/api/psi/$id/wait'
      preLoaderRoute: typeof ApiPsiIdWaitServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/peerjs/$key/peers': {
      id: '/api/peerjs/$key/peers'
      path: '/api/peerjs/$key/peers'
      fullPath: '/api/peerjs/$key/peers'
      preLoaderRoute: typeof ApiPeerjsKeyPeersServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PsiRoute: PsiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiPeerjsIdServerRoute: ApiPeerjsIdServerRoute,
  ApiPsiCreateServerRoute: ApiPsiCreateServerRoute,
  ApiPeerjsIndexServerRoute: ApiPeerjsIndexServerRoute,
  ApiPeerjsKeyPeersServerRoute: ApiPeerjsKeyPeersServerRoute,
  ApiPsiIdWaitServerRoute: ApiPsiIdWaitServerRoute,
  ApiPsiIdIndexServerRoute: ApiPsiIdIndexServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
