import fs from "node:fs";
import { z } from "zod";
import { SHARED_SECRET_REGEX, UsageError } from "@psilink/core";

import { warnIfFileOverPermissive, writeFileOwnerOnly } from "./fileUtils";
import { parseSensitiveJson } from "./sensitiveFile";

/**
 * Default path for the key file written by the provisioning commands (`invite`,
 * `accept`, and `exchange --save`). Matches the default the `exchange` command
 * reads from, so a key written here is found without an explicit `--key-file`.
 */
export const DEFAULT_KEY_PATH = "./.psilink.key";

/** Contents of a `.psilink.key` file. */
export interface KeyFile {
  /** Shared secret; injected into the connection config at runtime. */
  sharedSecret: string;
  /** ISO 8601 datetime after which the shared secret should be considered expired. */
  expires?: string;
}

const KeyFileSchema: z.ZodType<KeyFile> = z.object({
  sharedSecret: z
    .string()
    .regex(
      SHARED_SECRET_REGEX,
      "sharedSecret must be a base64url-encoded 32-byte value (43 base64url " +
        "characters; final character must be in [AEIMQUYcgkosw048]); " +
        "shared secrets are generated by 'psilink invite' - to obtain a new " +
        "one, both parties must re-invite",
    ),
  expires: z.iso.datetime().optional(),
});

/**
 * Load and parse a `.psilink.key` file; returns `undefined` if absent.
 *
 * `warnOnPermissive` (default `true`) emits the over-permissive-file warning. Set
 * it `false` only when re-reading a file already loaded (and warned about) this
 * run -- e.g. the post-exchange expiry re-check -- so the warning is not doubled.
 */
export function loadKeyFile(
  keyFilePath: string,
  opts: { warnOnPermissive?: boolean } = {},
): KeyFile | undefined {
  // Read, then parse through the sensitive-file chokepoint. A read failure (other
  // than ENOENT) propagates its errno -- a path plus code, no file content. The
  // JSON parse can echo a span of the source, and this file holds the shared
  // secret, so it routes through parseSensitiveJson, which reports path-only (see
  // sensitiveFile.ts). The KeyFileSchema error below names the field and its
  // format rule, never the value, so it is left to propagate.
  let source: string;
  try {
    source = fs.readFileSync(keyFilePath, "utf8");
  } catch (err: unknown) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw err;
  }
  const raw = parseSensitiveJson(source, `key file at ${keyFilePath}`);
  const result = KeyFileSchema.parse(raw);
  if (opts.warnOnPermissive !== false)
    warnIfFileOverPermissive(keyFilePath, "shared secret");
  return result;
}

/** Milliseconds in a day, for computing a rotated token's `expires`. */
const MS_PER_DAY = 86_400_000;

/**
 * Build the `.psilink.key` contents to persist after a successful key exchange.
 * When `tokenMaxAgeDays` is set, stamp `expires` = `now` + `tokenMaxAgeDays` days
 * (ISO 8601) so a rotated token cannot outlive the operator's max-age policy;
 * when omitted, the rotated token carries no `expires` (the unchanged default).
 *
 * `now` is a parameter rather than read internally so the stamp reflects the
 * actual moment of rotation (where the caller invokes it) and the helper stays
 * pure for testing.
 */
export function buildRotatedKeyFile(
  rotatedSecret: string,
  tokenMaxAgeDays: number | undefined,
  now: number,
): KeyFile {
  if (tokenMaxAgeDays === undefined) return { sharedSecret: rotatedSecret };
  // Belt-and-suspenders, mirroring saveKeyFile's runtime check below: the config
  // schema already enforces a positive integer (z.int().positive()), but a
  // library caller that bypasses parse could pass 0, a negative, or a float,
  // stamping an expiry that is immediately expired or on a sub-day boundary.
  // Reject it here so a broken expiry never reaches disk. UsageError -> CLI exit
  // 64, classified as bad input.
  if (!Number.isInteger(tokenMaxAgeDays) || tokenMaxAgeDays <= 0)
    throw new UsageError(
      "buildRotatedKeyFile: tokenMaxAgeDays must be a positive integer; got " +
        String(tokenMaxAgeDays),
    );
  // Guard the date-range overflow too. A value large enough that now + N days
  // leaves the representable Date range (or a 4-digit ISO year) would otherwise
  // make toISOString() throw an opaque RangeError -- here, after a successful
  // handshake the partner has already rotated against, with no clear cause and no
  // recovery short of editing the config. The config schema bounds this at the
  // front door (MAX_TOKEN_MAX_AGE_DAYS); this is the backstop for a caller that
  // bypasses parse, failing as bad input (UsageError -> exit 64) before the
  // broken expiry reaches disk, consistent with the positive-integer guard above.
  const expires = new Date(now + tokenMaxAgeDays * MS_PER_DAY);
  if (Number.isNaN(expires.getTime()) || expires.getUTCFullYear() > 9999)
    throw new UsageError(
      "buildRotatedKeyFile: tokenMaxAgeDays is too large; the computed expiry " +
        "is outside the supported date range",
    );
  return {
    sharedSecret: rotatedSecret,
    expires: expires.toISOString(),
  };
}

/** Result of {@link checkKeyFileExpiry}. */
export type KeyFileExpiryStatus = "ok" | "expiring-soon" | "expired";

/**
 * Classify a key file's expiry against the current time. Pure -- a function of
 * the key file and `now` only -- so it is straightforward to unit-test.
 *
 * - `"expired"`: `expires` is set and at or before `now`.
 * - `"expiring-soon"`: `expires` is set, still in the future, and the remaining
 *   time is at most `warnThresholdDays` days. Reachable only when a threshold is
 *   supplied; without one, an unexpired token is always `"ok"`.
 * - `"ok"`: no `expires`, `expires` far enough out, or no threshold given.
 *
 * `warnThresholdDays` is a key-file-agnostic input: the max-age policy
 * (`tokenMaxAgeDays`) is a connection-config concern, so the caller computes the
 * threshold and passes it here rather than this helper knowing the policy field.
 * Absent threshold means the caller cannot determine "expiring soon" (no max-age
 * policy is in force), so only the unconditional `"expired"` hard stop applies.
 */
export function checkKeyFileExpiry(
  keyFile: KeyFile,
  now: number,
  opts: { warnThresholdDays?: number } = {},
): KeyFileExpiryStatus {
  if (keyFile.expires === undefined) return "ok";
  const expiresMs = new Date(keyFile.expires).getTime();
  // Fail closed on an unparseable timestamp. loadKeyFile validates `expires` as an
  // ISO datetime, so this is unreachable through the CLI, but a direct caller that
  // bypasses that validation must not have a malformed value classified as "ok"
  // (NaN <= now is false, which would otherwise fall through). Treat it as expired
  // so the hard stop, not a silent pass, is the default for a security control.
  if (Number.isNaN(expiresMs) || expiresMs <= now) return "expired";
  const { warnThresholdDays } = opts;
  if (
    warnThresholdDays !== undefined &&
    expiresMs - now <= warnThresholdDays * MS_PER_DAY
  )
    return "expiring-soon";
  return "ok";
}

/** Serialize and write a {@link KeyFile} to disk, owner-read-only. */
export function saveKeyFile(keyFilePath: string, data: KeyFile): void {
  // Belt-and-suspenders runtime validation: the type system already requires
  // `sharedSecret` to be a string, and today's only caller (runProtocol) derives
  // it from HKDF and so always produces a valid base64url-encoded 32-byte
  // value. Another caller (`invite` / `accept`, via provisionConfigAndKey)
  // could write a malformed shared secret that loadKeyFile would later reject;
  // fail here instead so the malformed value never reaches disk.
  //
  // UsageError (not a plain Error) so the CLI catch sites classify it as a
  // caller/usage problem (exit 64) rather than a transport failure (exit 69) --
  // a malformed shared secret supplied via invite/accept is bad input, and
  // provisionConfigAndKey makes this the reachable write path.
  if (!SHARED_SECRET_REGEX.test(data.sharedSecret))
    throw new UsageError(
      "saveKeyFile: sharedSecret must be a base64url-encoded 32-byte value " +
        "(43 base64url characters; final character must be in " +
        "[AEIMQUYcgkosw048])",
    );
  writeFileOwnerOnly(keyFilePath, JSON.stringify(data, null, 2) + "\n");
}
