import fs from "node:fs";
import { z } from "zod";
import { PAKE_TOKEN_REGEX, UsageError } from "@psilink/core";

import { warnIfFileOverPermissive, writeFileOwnerOnly } from "./fileUtils";

/**
 * Default path for the key file written by the provisioning commands (`invite`,
 * `accept`, and `exchange --save`). Matches the default the `exchange` command
 * reads from, so a key written here is found without an explicit `--key-file`.
 */
export const DEFAULT_KEY_PATH = "./.psilink.key";

/** Contents of a `.psilink.key` file. */
export interface KeyFile {
  /** Shared SPAKE2 token; injected into the connection config at runtime. */
  pakeToken: string;
  /** ISO 8601 datetime after which the token should be considered expired. */
  expires?: string;
}

const KeyFileSchema: z.ZodType<KeyFile> = z.object({
  pakeToken: z
    .string()
    .regex(
      PAKE_TOKEN_REGEX,
      "pakeToken must be a base64url-encoded 32-byte value (43 base64url " +
        "characters; final character must be in [AEIMQUYcgkosw048]); " +
        "tokens are generated by 'psilink invite' - to obtain a new token, " +
        "both parties must re-invite",
    ),
  expires: z.iso.datetime().optional(),
});

/** Load and parse a `.psilink.key` file; returns `undefined` if absent. */
export function loadKeyFile(keyFilePath: string): KeyFile | undefined {
  let raw: unknown;
  try {
    raw = JSON.parse(fs.readFileSync(keyFilePath, "utf8"));
  } catch (err: unknown) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw err;
  }
  const result = KeyFileSchema.parse(raw);
  warnIfFileOverPermissive(keyFilePath, "PAKE token");
  return result;
}

/** Serialize and write a {@link KeyFile} to disk, owner-read-only. */
export function saveKeyFile(keyFilePath: string, data: KeyFile): void {
  // Belt-and-suspenders runtime validation: the type system already requires
  // `pakeToken` to be a string, and today's only caller (runProtocol) derives
  // it from HKDF and so always produces a valid base64url-encoded 32-byte
  // value. A future caller (e.g. `invite` / `accept`, not yet implemented)
  // could write a malformed token that loadKeyFile would later reject; fail
  // here instead so the malformed token never reaches disk.
  //
  // UsageError (not a plain Error) so the CLI catch sites classify it as a
  // caller/usage problem (exit 64) rather than a transport failure (exit 69) --
  // a malformed token supplied via invite/accept is bad input, and
  // provisionConfigAndKey makes this the reachable write path.
  if (!PAKE_TOKEN_REGEX.test(data.pakeToken))
    throw new UsageError(
      "saveKeyFile: pakeToken must be a base64url-encoded 32-byte value " +
        "(43 base64url characters; final character must be in " +
        "[AEIMQUYcgkosw048])",
    );
  writeFileOwnerOnly(keyFilePath, JSON.stringify(data, null, 2) + "\n");
}
