import { setFlagsFromString } from "node:v8";
import { runInNewContext } from "node:vm";
import { parentPort, workerData } from "node:worker_threads";

import { servePsiWorker } from "@psilink/core";
import type {
  PsiWorkerInit,
  PsiWorkerRequest,
  PsiWorkerResponse,
} from "@psilink/core";

import { loadCliPsiBackend } from "./psiBackend";

// Expose gc() in this worker so relievePsiWorkerMemory (@psilink/core) can force a
// collection of the per-op JS<->native marshalling churn -- the single-pass
// receiver's dominant transient cost, which now lives on this worker's heap rather
// than the main thread's. --expose-gc cannot be passed through a worker's execArgv
// (Node rejects it with ERR_WORKER_INVALID_EXEC_ARGV), and a parent exposes gc in
// its workers only when it was itself launched with --expose-gc, so enable it at
// runtime here whenever it is not already present. Without this relief the
// single-pass dataset ceiling would silently regress.
// Cast through unknown so `gc` is a plain optional function here rather than
// intersecting with globalThis's own GCFunction typing (which rejects the
// () => void assignment below).
const globalWithGc = globalThis as unknown as { gc?: () => void };
if (typeof globalWithGc.gc !== "function") {
  setFlagsFromString("--expose-gc");
  globalWithGc.gc = runInNewContext("gc") as () => void;
}

// worker_threads entry point that runs the PSI elliptic-curve masking off the CLI's
// event-loop-owning thread, so a multi-minute round no longer starves the SFTP
// heartbeat or the liveness timers (board item 208035324). It is seeded once with
// the participant's role and id through workerData, loads the same native-preferred
// backend the main thread would, then answers each request from the host
// WorkerPsiEngine. The secret key is generated by createWithNewKey inside
// servePsiWorker here and never leaves this worker.
async function main(): Promise<void> {
  const port = parentPort;
  if (!port)
    throw new Error("PSI worker started outside a worker_threads worker");
  const init = workerData as PsiWorkerInit;
  const { library } = await loadCliPsiBackend();
  const handle = servePsiWorker(library, init, (response: PsiWorkerResponse) =>
    port.postMessage(response),
  );
  // Messages the host posted while the backend was loading were queued on the port;
  // attaching the listener now drains them in order.
  port.on("message", (request: PsiWorkerRequest) => handle(request));
}

void main().catch((error: unknown) => {
  // The backend failed to load; there is nothing to serve. Report and exit non-zero
  // so the host's Worker 'exit' handler fails the exchange rather than leaving it to
  // hang on a dead worker.
  process.stderr.write(`PSI worker failed to start: ${String(error)}\n`);
  process.exit(1);
});
